version: 1
updates:
  - package-ecosystem: "pub"
    directory: "/"
    # Check the pub.dev registry for updates every month
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
